/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AresFitnessProfile {
  'experienceLevel' : [] | [string],
  'currentWeekCompletedDays' : Array<string>,
  'heightCm' : [] | [number],
  'goal' : [] | [string],
  'onboardingComplete' : boolean,
  'missedDaysCount' : bigint,
  'personalityMode' : string,
  'lastWorkoutDate' : [] | [string],
  'weightKg' : [] | [number],
  'dietType' : [] | [string],
}
export interface CallerProfile { 'name' : string, 'email' : string }
export interface ChatMessage {
  'id' : string,
  'mode' : string,
  'sender' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface CreateUserProfile {
  'username' : string,
  'password' : string,
  'email' : string,
}
export type Results = { 'ok' : null } |
  { 'err' : string };
export interface UpdateUserProfile {
  'username' : string,
  'email' : string,
  'passwordHash' : string,
}
export type UserId = bigint;
export interface UserProfile {
  'id' : [] | [UserId],
  'username' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'addAresChatMessage' : ActorMethod<[ChatMessage], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAresChatHistory' : ActorMethod<[], undefined>,
  'deleteUser' : ActorMethod<[UserId], Results>,
  'getAresChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getAresFitnessProfile' : ActorMethod<[], [] | [AresFitnessProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [CallerProfile]>,
  'getMyRole' : ActorMethod<[], UserRole>,
  'getUserByEmail' : ActorMethod<[string], [] | [UserProfile]>,
  'getUserById' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [CallerProfile]>,
  'getUsers' : ActorMethod<[], Array<UserProfile>>,
  'logWorkoutCompleted' : ActorMethod<[string], undefined>,
  'logWorkoutSkipped' : ActorMethod<[], undefined>,
  'login' : ActorMethod<[string, string], Results>,
  'register' : ActorMethod<[CreateUserProfile], Results>,
  'saveAresFitnessProfile' : ActorMethod<[AresFitnessProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[CallerProfile], undefined>,
  'updateUser' : ActorMethod<[UserId, UpdateUserProfile], Results>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];