/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChatMessage = IDL.Record({
  'id' : IDL.Text,
  'mode' : IDL.Text,
  'sender' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Nat;
export const Results = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const AresFitnessProfile = IDL.Record({
  'experienceLevel' : IDL.Opt(IDL.Text),
  'currentWeekCompletedDays' : IDL.Vec(IDL.Text),
  'heightCm' : IDL.Opt(IDL.Float64),
  'goal' : IDL.Opt(IDL.Text),
  'onboardingComplete' : IDL.Bool,
  'missedDaysCount' : IDL.Nat,
  'personalityMode' : IDL.Text,
  'lastWorkoutDate' : IDL.Opt(IDL.Text),
  'weightKg' : IDL.Opt(IDL.Float64),
  'dietType' : IDL.Opt(IDL.Text),
});
export const CallerProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Opt(UserId),
  'username' : IDL.Text,
  'email' : IDL.Text,
});
export const CreateUserProfile = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
  'email' : IDL.Text,
});
export const UpdateUserProfile = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
  'passwordHash' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAresChatMessage' : IDL.Func([ChatMessage], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAresChatHistory' : IDL.Func([], [], []),
  'deleteUser' : IDL.Func([UserId], [Results], []),
  'getAresChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getAresFitnessProfile' : IDL.Func(
      [],
      [IDL.Opt(AresFitnessProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(CallerProfile)], ['query']),
  'getMyRole' : IDL.Func([], [UserRole], ['query']),
  'getUserByEmail' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getUserById' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CallerProfile)],
      ['query'],
    ),
  'getUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'logWorkoutCompleted' : IDL.Func([IDL.Text], [], []),
  'logWorkoutSkipped' : IDL.Func([], [], []),
  'login' : IDL.Func([IDL.Text, IDL.Text], [Results], []),
  'register' : IDL.Func([CreateUserProfile], [Results], []),
  'saveAresFitnessProfile' : IDL.Func([AresFitnessProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([CallerProfile], [], []),
  'updateUser' : IDL.Func([UserId, UpdateUserProfile], [Results], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChatMessage = IDL.Record({
    'id' : IDL.Text,
    'mode' : IDL.Text,
    'sender' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Nat;
  const Results = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const AresFitnessProfile = IDL.Record({
    'experienceLevel' : IDL.Opt(IDL.Text),
    'currentWeekCompletedDays' : IDL.Vec(IDL.Text),
    'heightCm' : IDL.Opt(IDL.Float64),
    'goal' : IDL.Opt(IDL.Text),
    'onboardingComplete' : IDL.Bool,
    'missedDaysCount' : IDL.Nat,
    'personalityMode' : IDL.Text,
    'lastWorkoutDate' : IDL.Opt(IDL.Text),
    'weightKg' : IDL.Opt(IDL.Float64),
    'dietType' : IDL.Opt(IDL.Text),
  });
  const CallerProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const UserProfile = IDL.Record({
    'id' : IDL.Opt(UserId),
    'username' : IDL.Text,
    'email' : IDL.Text,
  });
  const CreateUserProfile = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
    'email' : IDL.Text,
  });
  const UpdateUserProfile = IDL.Record({
    'username' : IDL.Text,
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
  });
  
  return IDL.Service({
    'addAresChatMessage' : IDL.Func([ChatMessage], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAresChatHistory' : IDL.Func([], [], []),
    'deleteUser' : IDL.Func([UserId], [Results], []),
    'getAresChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getAresFitnessProfile' : IDL.Func(
        [],
        [IDL.Opt(AresFitnessProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(CallerProfile)], ['query']),
    'getMyRole' : IDL.Func([], [UserRole], ['query']),
    'getUserByEmail' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'getUserById' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CallerProfile)],
        ['query'],
      ),
    'getUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'logWorkoutCompleted' : IDL.Func([IDL.Text], [], []),
    'logWorkoutSkipped' : IDL.Func([], [], []),
    'login' : IDL.Func([IDL.Text, IDL.Text], [Results], []),
    'register' : IDL.Func([CreateUserProfile], [Results], []),
    'saveAresFitnessProfile' : IDL.Func([AresFitnessProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([CallerProfile], [], []),
    'updateUser' : IDL.Func([UserId, UpdateUserProfile], [Results], []),
  });
};

export const init = ({ IDL }) => { return []; };