/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Results = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type UserId = bigint;
export interface CallerProfile {
    name: string;
    email: string;
}
export interface ChatMessage {
    id: string;
    mode: string;
    sender: string;
    message: string;
    timestamp: bigint;
}
export interface UpdateUserProfile {
    username: string;
    email: string;
    passwordHash: string;
}
export interface AresFitnessProfile {
    experienceLevel?: string;
    currentWeekCompletedDays: Array<string>;
    heightCm?: number;
    goal?: string;
    onboardingComplete: boolean;
    missedDaysCount: bigint;
    personalityMode: string;
    lastWorkoutDate?: string;
    weightKg?: number;
    dietType?: string;
}
export interface CreateUserProfile {
    username: string;
    password: string;
    email: string;
}
export interface UserProfile {
    id?: UserId;
    username: string;
    email: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addAresChatMessage(msg: ChatMessage): Promise<void>;
    assignRole(user: Principal, role: UserRole): Promise<void>;
    clearAresChatHistory(): Promise<void>;
    deleteUser(id: UserId): Promise<Results>;
    getAresChatHistory(): Promise<Array<ChatMessage>>;
    getAresFitnessProfile(): Promise<AresFitnessProfile | null>;
    getCallerUserProfile(): Promise<CallerProfile | null>;
    getMyRole(): Promise<UserRole>;
    getUserByEmail(email: string): Promise<UserProfile | null>;
    getUserById(id: UserId): Promise<UserProfile | null>;
    getUserProfile(user: Principal): Promise<CallerProfile | null>;
    getUsers(): Promise<Array<UserProfile>>;
    logWorkoutCompleted(date: string): Promise<void>;
    logWorkoutSkipped(): Promise<void>;
    login(email: string, password: string): Promise<Results>;
    register(createUserProfile: CreateUserProfile): Promise<Results>;
    saveAresFitnessProfile(profile: AresFitnessProfile): Promise<void>;
    saveCallerUserProfile(profile: CallerProfile): Promise<void>;
    updateUser(id: UserId, profile: UpdateUserProfile): Promise<Results>;
}
import type { AresFitnessProfile as _AresFitnessProfile, CallerProfile as _CallerProfile, Results as _Results, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAresChatMessage(arg0: ChatMessage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAresChatMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAresChatMessage(arg0);
            return result;
        }
    }
    async assignRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearAresChatHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAresChatHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAresChatHistory();
            return result;
        }
    }
    async deleteUser(arg0: UserId): Promise<Results> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return from_candid_Results_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return from_candid_Results_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAresChatHistory(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAresChatHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAresChatHistory();
            return result;
        }
    }
    async getAresFitnessProfile(): Promise<AresFitnessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAresFitnessProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAresFitnessProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<CallerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByEmail(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByEmail(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByEmail(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserById(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserById(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserById(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<CallerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async logWorkoutCompleted(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logWorkoutCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWorkoutCompleted(arg0);
            return result;
        }
    }
    async logWorkoutSkipped(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logWorkoutSkipped();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWorkoutSkipped();
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<Results> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_Results_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_Results_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: CreateUserProfile): Promise<Results> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0);
                return from_candid_Results_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0);
            return from_candid_Results_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveAresFitnessProfile(arg0: AresFitnessProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAresFitnessProfile(to_candid_AresFitnessProfile_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAresFitnessProfile(to_candid_AresFitnessProfile_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: CallerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateUser(arg0: UserId, arg1: UpdateUserProfile): Promise<Results> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, arg1);
                return from_candid_Results_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, arg1);
            return from_candid_Results_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AresFitnessProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AresFitnessProfile): AresFitnessProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Results_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Results): Results {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CallerProfile]): CallerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AresFitnessProfile]): AresFitnessProfile | null {
    return value.length === 0 ? null : from_candid_AresFitnessProfile_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: [] | [_UserId];
    username: string;
    email: string;
}): {
    id?: UserId;
    username: string;
    email: string;
} {
    return {
        id: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.id)),
        username: value.username,
        email: value.email
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    experienceLevel: [] | [string];
    currentWeekCompletedDays: Array<string>;
    heightCm: [] | [number];
    goal: [] | [string];
    onboardingComplete: boolean;
    missedDaysCount: bigint;
    personalityMode: string;
    lastWorkoutDate: [] | [string];
    weightKg: [] | [number];
    dietType: [] | [string];
}): {
    experienceLevel?: string;
    currentWeekCompletedDays: Array<string>;
    heightCm?: number;
    goal?: string;
    onboardingComplete: boolean;
    missedDaysCount: bigint;
    personalityMode: string;
    lastWorkoutDate?: string;
    weightKg?: number;
    dietType?: string;
} {
    return {
        experienceLevel: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.experienceLevel)),
        currentWeekCompletedDays: value.currentWeekCompletedDays,
        heightCm: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.heightCm)),
        goal: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.goal)),
        onboardingComplete: value.onboardingComplete,
        missedDaysCount: value.missedDaysCount,
        personalityMode: value.personalityMode,
        lastWorkoutDate: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.lastWorkoutDate)),
        weightKg: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.weightKg)),
        dietType: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.dietType))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n14(_uploadFile, _downloadFile, x));
}
function to_candid_AresFitnessProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AresFitnessProfile): _AresFitnessProfile {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    experienceLevel?: string;
    currentWeekCompletedDays: Array<string>;
    heightCm?: number;
    goal?: string;
    onboardingComplete: boolean;
    missedDaysCount: bigint;
    personalityMode: string;
    lastWorkoutDate?: string;
    weightKg?: number;
    dietType?: string;
}): {
    experienceLevel: [] | [string];
    currentWeekCompletedDays: Array<string>;
    heightCm: [] | [number];
    goal: [] | [string];
    onboardingComplete: boolean;
    missedDaysCount: bigint;
    personalityMode: string;
    lastWorkoutDate: [] | [string];
    weightKg: [] | [number];
    dietType: [] | [string];
} {
    return {
        experienceLevel: value.experienceLevel ? candid_some(value.experienceLevel) : candid_none(),
        currentWeekCompletedDays: value.currentWeekCompletedDays,
        heightCm: value.heightCm ? candid_some(value.heightCm) : candid_none(),
        goal: value.goal ? candid_some(value.goal) : candid_none(),
        onboardingComplete: value.onboardingComplete,
        missedDaysCount: value.missedDaysCount,
        personalityMode: value.personalityMode,
        lastWorkoutDate: value.lastWorkoutDate ? candid_some(value.lastWorkoutDate) : candid_none(),
        weightKg: value.weightKg ? candid_some(value.weightKg) : candid_none(),
        dietType: value.dietType ? candid_some(value.dietType) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
